all:
  children:

    infra:
      hosts:
        pihole-01:
          ansible_host: 192.168.1.190
        vault:
          ansible_host: 192.168.1.191

    k0s_controllers:
      hosts:
        k0sm-00:
          ansible_host: 192.168.1.192

    k0s_workers:
      hosts:
        k0sw-00:
          ansible_host: 192.168.1.193
        k0sw-01:
          ansible_host: 192.168.1.194

    k0s:
      children:
        k0s_controllers:
        k0s_workers:
