all:
  children:

    infra:
      hosts:
        pihole-01:
          ansible_host: 192.168.1.6
        vault:
          ansible_host: 192.168.1.140
        nfs-01:
          ansible_host: 192.168.1.125

    nfs:
      hosts:
        nfs-01:
          ansible_host: 192.168.1.125

    proxmox_hosts:
      hosts:
        prox:
          ansible_host: 192.168.1.148
          ansible_user: root

    k0s_controllers:
      hosts:
        k0sm-00:
          ansible_host: 192.168.1.247

    k0s_workers:
      hosts:
        k0sw-00:
          ansible_host: 192.168.1.143
        k0sw-01:
          ansible_host: 192.168.1.135

    k0s:
      children:
        k0s_controllers:
        k0s_workers:
