apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  type: kv-v2
  mount: secret
  path: authentik/providers/argo
  destination:
    name: argocd-oidc-secret
    create: true
    labels:
      app.kubernetes.io/part-of: argocd
  vaultAuthRef: vault-auth
  refreshAfter: 1h
